# Project information
site_name: 'S-LDXR'
site_description: 'Estimating enrichment of stratified squared trans-ethnic genetic correlation'
site_author: 'Huwenbo Shi'
site_url: 'https://huwenboshi.github.io/s-ldxr'

# Repository
#repo_url: 'https://github.com/huwenboshi/s-ldxr'
repo_url: null

# Copyright
copyright: 'Copyright &copy; 2019 - 2024 Huwenbo Shi'

# Documentation and theme
theme: 'mkdocs'

# define pages
pages:
    - Home: 'index.md'
    - Input Format: 'input_format.md'
    - Estimation:
        - 'Estimating LD score': 'ldscore.md'
        - 'Estimating enrichment': 'gcorsq.md'
    - FAQ: 'faq.md'

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/huwenboshi'
    - type: 'twitter'
      link: 'https://twitter.com/shihuwenbo'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/john-doe'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - mdx_math
  - admonition
  - codehilite
  - toc

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
